version: '3'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8080"
    dns: 8.8.8.8  # Example DNS server (Google's public DNS)

    healthcheck:
      test: ["CMD", "pg_isready", "-h", "db", "-p", "5432", "-U", "postgres"]
      interval: 10s
      timeout: 50s
      retries: 5

    container_name: gatepasssystem

    volumes:
      - .:/gatepasssystem
      - media_volume:/gatepasssystem/media  

    #  - .:/app
      # Add this line to mount a volume for media files
    #  - media_volume:/app/media


    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=postgres
      - DJANGO_DB_USER=postgres
      - DJANGO_DB_PASSWORD=postgres

      - DJANGO_SUPERUSER_USERNAME=admingatepass
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=adminpassword

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
  

    networks:
      - default
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - "POSTGRES_HOST_AUTH_METHOD=trust"

    volumes:
      - postgres_data:/var/lib/postgresql/data

# Define volumes at the end
volumes:
  postgres_data:
  media_volume:

networks:
  default:
    driver: bridge
